version: '2'
services:
  app:
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb
  metabase:
    build:
      context: ./metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  mongodb:
    image: mongo
    container_name: tp-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    volumes:
      - ./mongo/data:/data/db
  postgres:
    image: postgres
    container_name: tp-postgres-container
    environment:
      POSTGRES_DB: lappis
      POSTGRES_USER: lappis
      POSTGRES_PASSWORD: lappis
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
