name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Executar Testes
      run: poetry run pytest

    - name: Lint
      run: poetry run flake8

    - name: Documentação
      run: |
        poetry run sphinx-build -b html docs docs/_build
        echo "Documentação gerada."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Publicar no PyPI
      env:
        POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
      run: |
        echo "//pypi.org/" > ~/.pypirc
        echo "[pypi]" >> ~/.pypirc
        echo "username = __token__" >> ~/.pypirc
        echo "password = $POETRY_PYPI_TOKEN" >> ~/.pypirc
        poetry publish --build

